CREATE OR ALTER PROC FI_SP_VerificaBeneficiario
 @CPF VARCHAR(14),
 @IDCLIENTE BIGINT
 AS  
BEGIN
	IF(ISNULL(@IDCLIENTE, 0) = 0)
	SELECT 1 FROM BENEFICIARIOS WITH(NOLOCK) WHERE CPF = @CPF
	ELSE
	SELECT 1 FROM BENEFICIARIOS WITH(NOLOCK) WHERE CPF = @CPF AND IDCLIENTE <> @IDCLIENTE
END