--CRIANDO UMA NOVA COLUNA 'CPF' NA TABELA CLIENTE
ALTER TABLE CLIENTES
	ADD CPF VARCHAR(14) NOT NULL

--CRIANDO UNIQUE KEY PARA TORNAR 'CPF' IMPOSSÍVEL DE DUPLICAR
ALTER TABLE CLIENTES
	ADD CONSTRAINT UQ_CPF UNIQUE (CPF)